apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "provisioner.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ template "provisioner.chart" . }}
    app.kubernetes.io/name: {{ template "provisioner.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
{{- if .Values.nodeLabels }}
  nodeLabelsForPV: |
   {{- range $label := .Values.nodeLabels }}
    - {{$label}}
   {{- end }}
{{- end }}
{{- if .Values.labelsForPV }}
  labelsForPV: |
   {{- range $label, $value := .Values.labelsForPV }}
    {{$label}} : {{$value}}
   {{- end }}
{{- end }}
{{- if .Values.setPVOwnerRef }}
  setPVOwnerRef: "true"
{{- end }}
{{- if .Values.useJobForCleaning }}
  useJobForCleaning: "yes"
{{- end }}
{{- if .Values.tolerations }}
  jobTolerations: | {{ toYaml .Values.tolerations | nindent 4 }}
{{- end }}
{{- if .Values.useNodeNameOnly }}
  useNodeNameOnly: "true"
{{- end }}
{{- if .Values.minResyncPeriod }}
  minResyncPeriod: {{ .Values.minResyncPeriod | quote }}
{{- end }}
  storageClassMap: |
    {{- range $classConfig := .Values.classes }}
    {{ $classConfig.name }}:
      hostDir: {{ $classConfig.hostDir }}
      mountDir: {{ $classConfig.mountDir | default $classConfig.hostDir }}
      {{- if $classConfig.blockCleanerCommand }}
      blockCleanerCommand:
      {{- range $val := $classConfig.blockCleanerCommand }}
        - {{ $val | quote }}
      {{- end }}
      {{- end }}
      {{- if $classConfig.volumeMode }}
      volumeMode: {{ $classConfig.volumeMode }}
      {{- end }}
      {{- if $classConfig.fsType }}
      fsType: {{ $classConfig.fsType }}
      {{- end }}
      {{- if $classConfig.namePattern }}
      namePattern: {{ $classConfig.namePattern | quote }}
      {{- end }}
      {{- if $classConfig.selector }}
      selector:
      {{- toYaml $classConfig.selector | nindent 8 }}
      {{- end }}
    {{- end }}
