apiVersion: v2
name: local-static-provisioner
description: Helm chart for the SIG Storage Local Volume Static Provisioner.
type: application
version: 2.8.0
appVersion: 2.8.0
keywords:
  - storage
  - local
  - volume
home: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/
icon: https://avatars.githubusercontent.com/u/36015203?s=200&v=4
sources:
  - https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/
