---
# Source: local-static-provisioner/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-static-provisioner
  namespace: default
  labels:
    helm.sh/chart: local-static-provisioner-1.0.0
    app.kubernetes.io/name: local-static-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: local-static-provisioner
---
# Source: local-static-provisioner/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-static-provisioner-config
  namespace: default
  labels:
    helm.sh/chart: local-static-provisioner-1.0.0
    app.kubernetes.io/name: local-static-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: local-static-provisioner
data:
  storageClassMap: |
    fast-disks:
      hostDir: /mnt/fast-disks
      mountDir: /mnt/fast-disks
      blockCleanerCommand:
        - "/scripts/shred.sh"
        - "2"
      volumeMode: Filesystem
      fsType: ext4
      namePattern: "*"
---
# Source: local-static-provisioner/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-static-provisioner-node-clusterrole
  labels:
    helm.sh/chart: local-static-provisioner-1.0.0
    app.kubernetes.io/name: local-static-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: local-static-provisioner
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["watch"]
- apiGroups: ["", "events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "update", "patch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
# Source: local-static-provisioner/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-static-provisioner-node-binding
  labels:
    helm.sh/chart: local-static-provisioner-1.0.0
    app.kubernetes.io/name: local-static-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: local-static-provisioner
subjects:
- kind: ServiceAccount
  name: local-static-provisioner
  namespace: default
roleRef:
  kind: ClusterRole
  name: local-static-provisioner-node-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
# Source: local-static-provisioner/templates/daemonset_linux.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: local-static-provisioner
  namespace: default
  labels:
    helm.sh/chart: local-static-provisioner-1.0.0
    app.kubernetes.io/name: local-static-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: local-static-provisioner
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: local-static-provisioner
      app.kubernetes.io/instance: local-static-provisioner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: local-static-provisioner
        app.kubernetes.io/instance: local-static-provisioner
      annotations:
        checksum/config: fbfc9e88fedc172393c69523b113ad18a015df9a3331a28ebd22fbddf52b4c8e
    spec:
      serviceAccountName: local-static-provisioner
      nodeSelector:
        kubernetes.io/os: linux
      initContainers:
        - args:
          - -c
          - /etc/init/run.sh
          command:
          - /bin/sh
          image: alpine:3
          name: test
          volumeMounts:
          - mountPath: /etc/init
            name: init-config
          - mountPath: /etc/signal
            name: signal
      containers:
        - name: provisioner
          image: registry.k8s.io/sig-storage/local-volume-provisioner:v2.5.0
          securityContext:
            privileged: true
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JOB_CONTAINER_IMAGE
            value: registry.k8s.io/sig-storage/local-volume-provisioner:v2.5.0
          ports:
          - name: metrics
            containerPort: 8080
          volumeMounts:
            - name: provisioner-config
              mountPath: /etc/provisioner/config
              readOnly: true
            - name: provisioner-dev
              mountPath: /dev
            - name: fast-disks
              mountPath: /mnt/fast-disks
              mountPropagation: HostToContainer
            - mountPath: /etc/signal
              name: signal
              readOnly: true
      volumes:
        - name: provisioner-config
          configMap:
            name: local-static-provisioner-config
        - name: provisioner-dev
          hostPath:
            path: /dev
        - name: fast-disks
          hostPath:
            path: /mnt/fast-disks
        - configMap:
            name: init-config
          name: init-config
        - emptyDir: {}
          name: signal
